const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const authSchema = new Schema({
    userId: {//User id from Twitch API
        type: String,
        required: true,
        unique: true //each user id must be unqiue
    },
    access_token: { //OAuth access token
        type: String,
        required: true
    },
    refresh_token: { //OAuth refresh token
        type: String,
        required: true
    },
    custom_token: { //custom token generated by server to authenticate client
        type: String,
        required: true
    }
}, { timestamps: true });

const AuthInfo = mongoose.model("authinfo", authSchema); //look for AuthInfos collection
module.exports = AuthInfo;
